---
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: build03-vqlvf
  name: build03-vqlvf-ci-tests-worker-us-east-1a
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: build03-vqlvf
      machine.openshift.io/cluster-api-machineset: build03-vqlvf-ci-tests-worker-us-east-1a
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: build03-vqlvf
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: build03-vqlvf-ci-tests-worker-us-east-1a
    spec:
      metadata:
        labels:
          ci-workload: tests
      providerSpec:
        value:
          ami:
            id: ami-0b35795bcab04ee70
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
          - ebs:
              volumeSize: 300
              volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: build03-vqlvf-worker-profile
          instanceType: m5.4xlarge
          kind: AWSMachineProviderConfig
          metadata:
            creationTimestamp: null
          placement:
            availabilityZone: us-east-1a
            region: us-east-1
          securityGroups:
          - filters:
            - name: tag:Name
              values:
              - build03-vqlvf-worker-sg
          subnet:
            filters:
            - name: tag:Name
              values:
              - build03-vqlvf-private-us-east-1a
          tags:
          - name: kubernetes.io/cluster/build03-vqlvf
            value: owned
          userDataSecret:
            name: worker-user-data
      taints:
      - effect: NoSchedule
        key: node-role.kubernetes.io/ci-tests-worker
        value: ci-tests-worker
---
apiVersion: autoscaling.openshift.io/v1beta1
kind: MachineAutoscaler
metadata:
  name: build03-vqlvf-ci-tests-worker-us-east-1a
  namespace: openshift-machine-api
spec:
  maxReplicas: 50
  minReplicas: 1
  scaleTargetRef:
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet
    name: build03-vqlvf-ci-tests-worker-us-east-1a
