---
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: build04-c92hb
  name: build04-c92hb-ci-tests-worker-b
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: build04-c92hb
      machine.openshift.io/cluster-api-machineset: build04-c92hb-ci-tests-worker-b
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: build04-c92hb
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: build04-c92hb-ci-tests-worker-b
    spec:
      metadata:
        labels:
          ci-workload: tests
      providerSpec:
        value:
          apiVersion: machine.openshift.io/v1beta1
          canIPForward: false
          credentialsSecret:
            name: gcp-cloud-credentials
          deletionProtection: false
          disks:
          - autoDelete: true
            boot: true
            image: projects/rhcos-cloud/global/images/rhcos-49-84-202110081407-0-gcp-x86-64
            sizeGb: 128
            type: pd-ssd
          kind: GCPMachineProviderSpec
          machineType: custom-16-65536
          metadata:
            creationTimestamp: null
          networkInterfaces:
          - network: build04-c92hb-network
            subnetwork: build04-c92hb-worker-subnet
          projectID: openshift-ci-build-farm
          region: us-east1
          serviceAccounts:
          - email: build04-c92hb-w@openshift-ci-build-farm.iam.gserviceaccount.com
            scopes:
            - https://www.googleapis.com/auth/cloud-platform
          tags:
          - build04-c92hb-worker
          userDataSecret:
            name: worker-user-data
          zone: us-east1-b
      taints:
      - effect: NoSchedule
        key: node-role.kubernetes.io/ci-tests-worker
        value: ci-tests-worker
---
apiVersion: autoscaling.openshift.io/v1beta1
kind: MachineAutoscaler
metadata:
  name: build04-c92hb-ci-tests-worker-b
  namespace: openshift-machine-api
spec:
  maxReplicas: 50
  minReplicas: 1
  scaleTargetRef:
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet
    name: build04-c92hb-ci-tests-worker-b