---
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: build01-9hdwj
  name: build01-9hdwj-ci-tests-worker-us-east-1d
  namespace: openshift-machine-api
spec:
  deletePolicy: Oldest
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: build01-9hdwj
      machine.openshift.io/cluster-api-machineset: build01-9hdwj-ci-tests-worker-us-east-1d
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: build01-9hdwj
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: build01-9hdwj-ci-tests-worker-us-east-1d
    spec:
      metadata:
        labels:
          ci-workload: tests
      taints:
      - key: node-role.kubernetes.io/ci-tests-worker
        effect: NoSchedule
      providerSpec:
        value:
          ami:
            id: ami-06f85a7940faa3217
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
          - ebs:
              volumeSize: 300
              volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: build01-9hdwj-worker-profile
          instanceType: m5.4xlarge
          kind: AWSMachineProviderConfig
          metadata: {}
          placement:
            availabilityZone: us-east-1d
            region: us-east-1
          securityGroups:
          - filters:
            - name: tag:Name
              values:
              - build01-9hdwj-worker-sg
          subnet:
            filters:
            - name: tag:Name
              values:
              - build01-9hdwj-private-us-east-1d
          tags:
          - name: kubernetes.io/cluster/build01-9hdwj
            value: owned
          userDataSecret:
            name: worker-user-data
---
apiVersion: autoscaling.openshift.io/v1beta1
kind: MachineAutoscaler
metadata:
  name: build01-9hdwj-ci-tests-worker-us-east-1d
  namespace: openshift-machine-api
spec:
  maxReplicas: 40
  minReplicas: 0
  scaleTargetRef:
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet
    name: build01-9hdwj-ci-tests-worker-us-east-1d



