apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker 
  name: 99-z-ci-kubelet
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
      - contents:
          source: data:text/plain,NODE_SIZING_ENABLED%3Dfalse%0ASYSTEM_RESERVED_MEMORY%3D10Gi%0ASYSTEM_RESERVED_CPU%3D6000m%0A
        mode: 420
        overwrite: true
        path: /etc/node-sizing-enabled.env

