apiVersion: kubescheduler.config.k8s.io/v1beta2
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: false
profiles:
- schedulerName: trimaran
  plugins:
    score:
      disabled:
      - name: NodeResourcesBalancedAllocation
      - name: NodeResourcesLeastAllocated
      enabled:
      - name: TargetLoadPacking
        weight: 1
  pluginConfig:
    - name: TargetLoadPacking
      args:
        targetUtilization: 15
        defaultRequestsMultiplier: "1"
        defaultRequests:
          cpu: "100m"
