---
apiVersion: v1
kind: Namespace
metadata:
  name: ci-op-jmp
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox2
  namespace: ci-op-jmp
spec:
  schedulerName: trimaran
  containers:
  - name: busybox
    image: busybox
    command:
    - sleep
    - "10"
    resources:
      limits:
        memory: 1Gi
        cpu: 200m
      requests:
        memory: 1Gi
  terminationGracePeriodSeconds: 0
  restartPolicy: Never
