---
apiVersion: v1
kind: Namespace
metadata:
  name: jmp-next
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: jmp-next
spec:
  schedulerName: next
  containers:
  - name: busybox
    image: busybox
    command:
    - sleep
    - "10"
    resources:
      requests:
        cpu: 16
  terminationGracePeriodSeconds: 0
  restartPolicy: Never
